# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import a_queue as module_0


def test_case_0():
    queue_0 = module_0.Queue()
    var_0 = queue_0.peek()


@pytest.mark.xfail(strict=True)
def test_case_1():
    queue_0 = module_0.Queue()
    var_0 = queue_0.enqueue(queue_0)
    var_0.pop()


@pytest.mark.xfail(strict=True)
def test_case_2():
    queue_0 = module_0.Queue()
    var_0 = queue_0.size()
    bool_0 = False
    queue_1 = module_0.Queue(bool_0)
    queue_2 = module_0.Queue(bool_0)
    queue_2.dequeue()


def test_case_3():
    queue_0 = module_0.Queue()
    var_0 = queue_0.peek()
    queue_1 = module_0.Queue()
    var_1 = queue_1.size()
