# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import edit_distance as module_0
import builtins as module_1


def test_case_0():
    str_0 = "\\O#q*4>m?3"
    var_0 = module_0.calculate_edit_distance(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = ""
    var_0 = module_0.calculate_edit_distance(str_0, str_0)
    module_0.calculate_edit_distance(str_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    module_0.calculate_edit_distance(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "4w*X9_"
    str_1 = ")4w*X9_"
    var_0 = module_0.calculate_edit_distance(str_0, str_1)
    module_1.object(*var_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "4w*X9_"
    str_1 = "\x0b\"C.'"
    var_0 = module_0.calculate_edit_distance(str_0, str_1)
    module_0.calculate_edit_distance(str_0, var_0)
