# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import breadth_first_search as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    list_0 = [bool_0, bool_0]
    str_0 = "*\r"
    var_0 = module_0.breadth_first_search(str_0, list_0, str_0)
    var_1 = module_0.breadth_first_search(str_0, list_0, var_0)
    module_0.breadth_first_search_graph(bool_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    dict_0 = {}
    dict_1 = {}
    module_0.breadth_first_search_graph(dict_1, dict_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.breadth_first_search(none_type_0, none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    dict_0 = {}
    var_0 = module_0.breadth_first_search(dict_0, dict_0, dict_0)
    module_0.breadth_first_search_graph(var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = False
    module_0.breadth_first_search_graph(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    none_type_0 = None
    module_0.breadth_first_search_graph(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    bool_0 = True
    bytes_0 = b"\x82O\x90\xd5p\x1a\xb3\xf5\xe0iR\x9f\x96\xa6\xb8uTh"
    module_0.breadth_first_search_graph(bytes_0, bool_0)


def test_case_7():
    bool_0 = False
    list_0 = [bool_0, bool_0, bool_0, bool_0]
    list_1 = [list_0, bool_0, bool_0, bool_0]
    var_0 = module_0.breadth_first_search(list_1, list_0, bool_0)
