# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import radixsort as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"_\x86j\x18\xbd\xd1]J\xd0\x0c\xb4\x00\xc6h\xaaj\x19\x8f\xc7\xd0"
    var_0 = module_0.radixsort(bytes_0)
    list_0 = module_0.radixsort(bytes_0)
    module_1.object(**var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    list_0 = [none_type_0, none_type_0, none_type_0, none_type_0]
    module_0.radixsort(list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    float_0 = -2376.0
    list_0 = [float_0, float_0]
    var_0 = module_0.radixsort(list_0, float_0)
    list_1 = [float_0]
    var_1 = module_0.radixsort(list_1)
    module_0.radixsort(float_0)
