# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import permutations as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "zm5\\^o${"
    var_0 = module_0.permutations_of_word(str_0)
    none_type_0 = None
    module_0.permutations_of_word(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.permutations_of_word(none_type_0)
