# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import fizz_buzz as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    int_0 = 2370
    var_0 = module_0.fizz_buzz(int_0)
    module_0.fizz_buzz(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    var_0 = module_0.fizz_buzz(bool_0)
    module_0.fizz_buzz(var_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    float_0 = -541.5
    module_0.fizz_buzz(float_0)
