# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import first_missing_positive as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    float_0 = 408.0
    list_0 = []
    var_0 = module_0.first_missing_positive(list_0)
    assert var_0 == 1
    module_0.first_missing_positive(float_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b'\xe0\xc8"\xefS\x8b\x0b'
    module_0.first_missing_positive(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"\x05\x8b3\xbex\xd6\x82\xb1I;M~\xcf\xbb\xcf)\xf1\xae"
    module_0.first_missing_positive(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b"\x05\x8b3\xbex\xd6\x82\xb1I;M~\xcf\xbb\xcf)\xc0\xae"
    module_0.first_missing_positive(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    float_0 = -3237.7
    list_0 = [float_0, float_0, float_0, float_0]
    var_0 = module_0.first_missing_positive(list_0)
    assert var_0 == 1
    list_1 = [var_0, var_0, float_0]
    var_1 = module_0.first_missing_positive(list_1)
    assert var_1 == 2
    module_1.object(*list_0)
