# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import heapsort as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    list_0 = [bool_0, bool_0]
    var_0 = module_0.heap_sort(list_0)
    module_0.custom_heap_sort(bool_0, bool_0)


def test_case_1():
    list_0 = []
    var_0 = module_0.heap_sort(list_0)


def test_case_2():
    bool_0 = True
    list_0 = [bool_0]
    var_0 = module_0.max_heap_sort(list_0)
    var_1 = module_0.max_heap_sort(list_0)


def test_case_3():
    list_0 = []
    var_0 = module_0.max_heap_sort(list_0)


def test_case_4():
    list_0 = []
    var_0 = module_0.custom_heap_sort(list_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    float_0 = 1790.173978
    module_0.custom_heap_sort(float_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    bool_0 = False
    bytes_0 = b"=\x17\xa0J8\xe2\x8c4f,\xcc"
    list_0 = []
    tuple_0 = (bool_0, bytes_0, list_0)
    list_1 = [tuple_0]
    var_0 = module_0.custom_heap_sort(list_1)
    bytes_1 = b"\x8e\xcb\xaf}\xdcT"
    tuple_1 = (bytes_1, bytes_1, bytes_1)
    list_2 = [tuple_1, bytes_1, tuple_1]
    module_0.custom_heap_sort(list_2, list_2)


@pytest.mark.xfail(strict=True)
def test_case_7():
    none_type_0 = None
    module_0.max_heap_sort(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    bool_0 = True
    module_0.heap_sort(bool_0)
