# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import dijkstras as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 2627
    module_0.dijkstras(int_0, int_0, int_0)
