# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import rabin_karp_substring_search as module_0


def test_case_0():
    str_0 = "Bod2?F7=\t\r_j{Tix`>"
    var_0 = module_0.rabin_karp_find_substring(str_0, str_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.rabin_karp_find_substring(
        none_type_0, none_type_0, prime_modulus=none_type_0
    )


def test_case_2():
    str_0 = "6\x0b3+"
    str_1 = "Np\x0cK`m$(lyi?B|yNSv"
    var_0 = module_0.rabin_karp_find_substring(str_1, str_0)
    assert var_0 == -1
