# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import depth_first_search as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    none_type_0 = None
    int_0 = -2106
    set_0 = {int_0, int_0, bool_0, int_0}
    bool_1 = True
    module_0.depth_first_search(set_0, bool_1, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "T"
    bool_0 = False
    bool_1 = False
    tuple_0 = (bool_0, bool_0, bool_1, bool_1)
    var_0 = module_0.depth_first_search(str_0, tuple_0, tuple_0)
    var_1 = module_0.depth_first_search(str_0, tuple_0, str_0)
    list_0 = []
    bool_2 = True
    var_2 = module_0.depth_first_search(list_0, bool_2, var_1)
    var_3 = module_0.depth_first_search(list_0, list_0, str_0)
    module_0.depth_first_search(str_0, str_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "<F"
    bool_0 = False
    complex_0 = -1571.7621 - 272.26252j
    bool_1 = True
    tuple_0 = (bool_0, bool_0, complex_0, bool_1)
    var_0 = module_0.depth_first_search(str_0, tuple_0, tuple_0)
    var_1 = module_0.depth_first_search(str_0, tuple_0, str_0)
    list_0 = []
    bool_2 = True
    var_2 = module_0.depth_first_search(list_0, bool_2, var_1)
    var_3 = module_0.depth_first_search(list_0, list_0, str_0)
    module_0.depth_first_search(str_0, str_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_0.depth_first_search(none_type_0, none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    list_0 = []
    var_0 = module_0.depth_first_search(list_0, list_0, list_0)
    tuple_0 = (var_0, var_0, list_0)
    module_1.object(*tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bytes_0 = b"/\xa0"
    module_0.depth_first_search(bytes_0, bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    int_0 = 2143
    dict_0 = {int_0: int_0, int_0: int_0, int_0: int_0, int_0: int_0}
    tuple_0 = (int_0, dict_0)
    tuple_1 = (tuple_0,)
    tuple_2 = (tuple_1, int_0)
    none_type_0 = None
    module_0.depth_first_search(tuple_2, dict_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    none_type_0 = None
    module_0.depth_first_search(none_type_0, none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    none_type_0 = None
    module_0.depth_first_search(none_type_0, none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_9():
    none_type_0 = None
    module_0.depth_first_search(none_type_0, none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_10():
    none_type_0 = None
    module_0.depth_first_search(none_type_0, none_type_0, none_type_0)
