# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import a_queue as module_0


def test_case_0():
    queue_0 = module_0.Queue()
    var_0 = queue_0.peek()


def test_case_1():
    queue_0 = module_0.Queue()


def test_case_2():
    queue_0 = module_0.Queue()
    var_0 = queue_0.enqueue(queue_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    queue_0 = module_0.Queue()
    queue_0.dequeue()


def test_case_4():
    queue_0 = module_0.Queue()
    var_0 = queue_0.size()
