# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import fizz_buzz as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 1415
    var_0 = module_0.fizz_buzz(int_0)
    var_1 = module_0.fizz_buzz(int_0)
    module_0.fizz_buzz(var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    var_0 = module_0.fizz_buzz(bool_0)
    bytes_0 = b"\x10\xf7_m\x97\xbeb\xf3.\xabc"
    module_0.fizz_buzz(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = -870
    var_0 = module_0.fizz_buzz(int_0)
    module_0.fizz_buzz(var_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    float_0 = -335.788283
    module_0.fizz_buzz(float_0)
