# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import radixsort as module_0


def test_case_0():
    int_0 = 201
    list_0 = [int_0, int_0, int_0]
    var_0 = module_0.radixsort(list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    list_0 = [bool_0]
    var_0 = module_0.radixsort(list_0)
    module_0.radixsort(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = '8."Y`pi"R0Wo^~'
    module_0.radixsort(str_0, str_0)
