# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import find_duplicates as module_0
import binary_search as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    module_0.duplicates_pre_sorted(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    dict_0 = {}
    var_0 = module_0.duplicates_bin_search(dict_0, dict_0)
    str_0 = 'Wk/- 5[3>yEo!#4"HaJ'
    var_1 = module_0.duplicates_pre_sorted(str_0, str_0)
    bytes_0 = b"\xe8\x9a;\xc6\x9a\xda\xd0\xcc\xe9C9M]\xc7\x99\xff"
    var_2 = module_0.duplicates_pre_sorted(dict_0, bytes_0)
    var_3 = module_0.duplicates_bin_search(var_1, var_1)
    var_4 = module_0.duplicates_linear(var_1, bytes_0)
    var_5 = module_0.duplicates_bin_search(var_2, var_4)
    var_6 = module_0.duplicates_linear(var_1, var_1)
    var_7 = module_0.duplicates_pre_sorted(var_6, var_6)
    var_8 = module_0.duplicates_pre_sorted(var_7, var_3)
    bool_0 = False
    module_0.duplicates_pre_sorted(bool_0, var_2)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "(TCgEdk26:"
    list_0 = [str_0, str_0, str_0]
    var_0 = module_0.duplicates_pre_sorted(list_0, str_0)
    var_1 = module_0.duplicates_pre_sorted(list_0, list_0)
    float_0 = 819.0
    module_0.duplicates_linear(float_0, float_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    tuple_0 = ()
    none_type_0 = None
    module_0.duplicates_bin_search(tuple_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bytes_0 = b"1"
    var_0 = module_0.duplicates_linear(bytes_0, bytes_0)
    var_1 = module_0.duplicates_bin_search(var_0, var_0)
    complex_0 = 1030.04376 - 1567.133j
    var_2 = module_0.duplicates_bin_search(var_0, var_1)
    var_3 = module_0.duplicates_linear(var_0, var_2)
    var_4 = module_0.duplicates_pre_sorted(var_0, var_2)
    module_0.duplicates_pre_sorted(var_1, complex_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bytes_0 = b"\xaa/\xc4"
    var_0 = module_0.duplicates_linear(bytes_0, bytes_0)
    complex_0 = 1026.290217127096 - 1567.133j
    var_1 = module_0.duplicates_bin_search(var_0, bytes_0)
    var_2 = module_0.duplicates_linear(var_0, var_1)
    var_3 = module_0.duplicates_pre_sorted(var_0, var_1)
    module_0.duplicates_pre_sorted(var_2, complex_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    str_0 = "\\CSn>\t`"
    var_0 = module_0.duplicates_bin_search(str_0, str_0)
    var_1 = module_0.duplicates_pre_sorted(var_0, var_0)
    bytes_0 = b"\x94\x96"
    var_2 = module_0.duplicates_pre_sorted(bytes_0, bytes_0)
    int_0 = -2006
    module_0.duplicates_linear(var_1, int_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    bool_0 = True
    none_type_0 = None
    module_1.binary_search(bool_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    none_type_0 = None
    module_0.duplicates_bin_search(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_9():
    dict_0 = {}
    var_0 = module_0.duplicates_pre_sorted(dict_0, dict_0)
    var_1 = module_0.duplicates_bin_search(dict_0, dict_0)
    var_2 = module_0.duplicates_linear(dict_0, dict_0)
    var_3 = module_0.duplicates_bin_search(var_1, var_0)
    var_4 = module_0.duplicates_pre_sorted(var_2, var_1)
    str_0 = 'A9b?oSSW|&\\mdOuO"'
    var_5 = module_0.duplicates_pre_sorted(str_0, dict_0)
    var_6 = module_0.duplicates_linear(dict_0, str_0)
    var_7 = module_0.duplicates_linear(dict_0, var_1)
    var_8 = module_0.duplicates_linear(var_4, var_5)
    var_9 = module_0.duplicates_pre_sorted(dict_0, dict_0)
    var_10 = module_0.duplicates_pre_sorted(var_5, var_0)
    list_0 = [var_3, var_5]
    var_11 = module_0.duplicates_bin_search(list_0, var_0)
    complex_0 = -542 - 1194.88j
    var_12 = module_0.duplicates_pre_sorted(str_0, var_9)
    var_13 = module_0.duplicates_pre_sorted(var_2, var_12)
    var_14 = module_0.duplicates_bin_search(var_0, var_0)
    var_15 = module_0.duplicates_bin_search(var_5, var_12)
    none_type_0 = None
    var_16 = module_0.duplicates_linear(var_0, var_3)
    module_0.duplicates_linear(complex_0, none_type_0)
