# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import linked_list2 as module_0
import stack as module_1


def test_case_0():
    linked_list_0 = module_0.LinkedList()
    linked_list_0.pop()


def test_case_1():
    stack_0 = module_1.Stack()
    linked_list_0 = module_0.LinkedList()
    var_0 = linked_list_0.size()
    var_0.pop()


def test_case_2():
    none_type_0 = None
    stack_0 = module_1.Stack()
    var_0 = stack_0.push(none_type_0)
    linked_list_0 = module_0.LinkedList()
    linked_list_0.pop()


def test_case_3():
    stack_0 = module_1.Stack()
    stack_0.pop()
