# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import stack as module_0


def test_case_0():
    none_type_0 = None
    stack_0 = module_0.Stack()
    stack_1 = module_0.Stack(none_type_0)
    stack_1.pop()


def test_case_1():
    none_type_0 = None
    stack_0 = module_0.Stack()
    var_0 = stack_0.push(none_type_0)
    stack_1 = module_0.Stack(none_type_0)
    stack_1.pop()
