[cosmic-ray]
module-path = "first_missing_positive.py"
timeout = 60.0
excluded-modules = []
test-command = "python -m pytest --tb=no ./ts-3-5/test_3-5_0-4_132.py"

[cosmic-ray.distributor]
name = "local"
