# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import rabin_karp_substring_search as module_0


def test_case_0():
    str_0 = "\tdw$K6e9hR()_Q"
    var_0 = module_0.rabin_karp_find_substring(str_0, str_0)
    assert var_0 == 0


def test_case_1():
    set_0 = set()
    var_0 = module_0.rabin_karp_find_substring(set_0, set_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.rabin_karp_find_substring(
        none_type_0, none_type_0, prime_modulus=none_type_0
    )


def test_case_3():
    str_0 = "*Q~z'&KS/5aMcsX\th0#S"
    str_1 = "*Q~z'&1S/5aMcsX\th0#S"
    var_0 = module_0.rabin_karp_find_substring(str_1, str_0)
    assert var_0 == -1


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "\tdw$K6e9hR()_6Q"
    str_1 = "a|U`G"
    var_0 = module_0.rabin_karp_find_substring(str_0, str_1)
    assert var_0 == -1
    none_type_0 = None
    module_0.rabin_karp_find_substring(none_type_0, none_type_0, none_type_0)


def test_case_5():
    str_0 = "*Q~z'&KS/5aMcsX\th0#S"
    str_1 = "*Q~z'&1S/5aMcsX\th0#S"
    bool_0 = False
    var_0 = module_0.rabin_karp_find_substring(str_1, str_0, bool_0)
    assert var_0 == -1
    var_1 = module_0.rabin_karp_find_substring(str_1, str_0)
    assert var_1 == -1
