[cosmic-ray]
module-path = "breadth_first_search.py"
timeout = 60.0
excluded-modules = []
test-command = "python -m pytest --tb=no ./ts-3-5/test_3-5_1-0_301.py"

[cosmic-ray.distributor]
name = "local"
