[cosmic-ray]
module-path = "rabin_karp_substring_search.py"
timeout = 60.0
excluded-modules = []
test-command = "python -m pytest --tb=no ./ts-3-5/test_3-5_0-8_244.py"

[cosmic-ray.distributor]
name = "local"
