# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import permutations as module_0


def test_case_0():
    str_0 = "Kh"
    var_0 = module_0.permutations_of_word(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    module_0.permutations_of_word(bool_0)
