# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import edit_distance as module_0
import builtins as module_1


def test_case_0():
    str_0 = "&"
    var_0 = module_0.calculate_edit_distance(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = ""
    var_0 = module_0.calculate_edit_distance(str_0, str_0)
    module_0.calculate_edit_distance(str_0, var_0)


def test_case_2():
    str_0 = "PE?+Ez(*V+;;9)4/>"
    var_0 = module_0.calculate_edit_distance(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    module_0.calculate_edit_distance(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "`[K428s&o<da!"
    var_0 = module_0.calculate_edit_distance(str_0, str_0)
    str_1 = "?49LG]^Ae"
    var_1 = module_0.calculate_edit_distance(str_0, str_1)
    module_0.calculate_edit_distance(var_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "R-N*Iq"
    var_0 = module_0.calculate_edit_distance(str_0, str_0)
    str_1 = "?49LG]^Ae"
    var_1 = module_0.calculate_edit_distance(str_0, str_1)
    var_2 = module_1.object()
    var_3 = module_0.calculate_edit_distance(str_1, str_0)
    module_0.calculate_edit_distance(var_2, var_2)
