# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import breadth_first_search as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"n\xac\xe20\x1e ="
    set_0 = {bytes_0, bytes_0, bytes_0}
    module_0.breadth_first_search(set_0, bytes_0, bytes_0)


def test_case_1():
    list_0 = []
    var_0 = module_0.breadth_first_search(list_0, list_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    module_0.breadth_first_search_graph(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = False
    list_0 = [bool_0, bool_0]
    list_1 = [list_0, bool_0, bool_0, bool_0]
    module_0.breadth_first_search(list_1, list_0, list_1)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = True
    list_0 = [bool_0, bool_0]
    list_1 = [list_0, list_0, bool_0, bool_0, bool_0, bool_0]
    module_0.breadth_first_search(list_1, list_0, list_1)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = False
    list_0 = [bool_0, bool_0]
    list_1 = [list_0, list_0, bool_0, bool_0]
    module_0.breadth_first_search(list_1, list_0, list_1)


def test_case_6():
    bool_0 = False
    list_0 = [bool_0, bool_0]
    list_1 = [list_0, list_0, bool_0, bool_0]
    var_0 = module_0.breadth_first_search(list_1, list_0, bool_0)
