[cosmic-ray]
module-path = "longest_common_prefix.py"
timeout = 60.0
excluded-modules = []
test-command = "python -m pytest --tb=no ./ts-3-5/test_3-5_0-2_65.py"

[cosmic-ray.distributor]
name = "local"
